var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/book/[businessId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__36cceaa3._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_9e498f65._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a7e6c3bd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d8001078._.js")
R.c("server/chunks/ssr/node_modules_0ecec565._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8be095de._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_book_[businessId]_page_actions_99f8fcb8.js")
R.m(94282)
module.exports=R.m(94282).exports
