var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/facilities/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d1a9e2b6._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_e9d66854._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a7e6c3bd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d8001078._.js")
R.c("server/chunks/ssr/node_modules_0ecec565._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8be095de._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_facilities_page_actions_941b307d.js")
R.m(17057)
module.exports=R.m(17057).exports
