// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/account/notifications" | "/account/profile" | "/book/[businessId]" | "/book/verify/[token]" | "/bookings/my-bookings" | "/businesses/[id]" | "/contact" | "/dashboard" | "/dashboard/[businessId]" | "/dashboard/analytics" | "/dashboard/bookings" | "/dashboard/bookings/[id]" | "/dashboard/business-hours" | "/dashboard/payments" | "/dashboard/services" | "/dashboard/settings" | "/dashboard/staff" | "/dashboard/subscription" | "/facilities" | "/forgot-password" | "/help" | "/login" | "/notification" | "/privacy" | "/register-business" | "/reset-password" | "/search" | "/setup-business" | "/signup" | "/signup-business" | "/sitemap" | "/staff/[staffCode]/book" | "/staff/[staffCode]/bookings" | "/staff/dashboard" | "/staff/login" | "/staff/request-reset" | "/staff/set-password" | "/staff/verify-email" | "/subscription" | "/subscription/expired" | "/terms" | "/verify-email"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/account/notifications": {}
  "/account/profile": {}
  "/book/[businessId]": { "businessId": string; }
  "/book/verify/[token]": { "token": string; }
  "/bookings/my-bookings": {}
  "/businesses/[id]": { "id": string; }
  "/contact": {}
  "/dashboard": {}
  "/dashboard/[businessId]": { "businessId": string; }
  "/dashboard/analytics": {}
  "/dashboard/bookings": {}
  "/dashboard/bookings/[id]": { "id": string; }
  "/dashboard/business-hours": {}
  "/dashboard/payments": {}
  "/dashboard/services": {}
  "/dashboard/settings": {}
  "/dashboard/staff": {}
  "/dashboard/subscription": {}
  "/facilities": {}
  "/forgot-password": {}
  "/help": {}
  "/login": {}
  "/notification": {}
  "/privacy": {}
  "/register-business": {}
  "/reset-password": {}
  "/search": {}
  "/setup-business": {}
  "/signup": {}
  "/signup-business": {}
  "/sitemap": {}
  "/staff/[staffCode]/book": { "staffCode": string; }
  "/staff/[staffCode]/bookings": { "staffCode": string; }
  "/staff/dashboard": {}
  "/staff/login": {}
  "/staff/request-reset": {}
  "/staff/set-password": {}
  "/staff/verify-email": {}
  "/subscription": {}
  "/subscription/expired": {}
  "/terms": {}
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
