// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/account/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/notifications">> = Specific
  const handler = {} as typeof import("../../../app/account/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/account/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/profile">> = Specific
  const handler = {} as typeof import("../../../app/account/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/[businessId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/[businessId]">> = Specific
  const handler = {} as typeof import("../../../app/book/[businessId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/book/verify/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book/verify/[token]">> = Specific
  const handler = {} as typeof import("../../../app/book/verify/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bookings/[businessId]/details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/[businessId]/details">> = Specific
  const handler = {} as typeof import("../../../app/bookings/[businessId]/details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/bookings/my-bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings/my-bookings">> = Specific
  const handler = {} as typeof import("../../../app/bookings/my-bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/businesses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/businesses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/businesses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/[businessId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[businessId]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/[businessId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/bookings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/bookings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/business-hours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/business-hours">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/business-hours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/payments">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/services">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/subscription">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/facilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/facilities">> = Specific
  const handler = {} as typeof import("../../../app/facilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../../app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/notification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notification">> = Specific
  const handler = {} as typeof import("../../../app/notification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/register-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register-business">> = Specific
  const handler = {} as typeof import("../../../app/register-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/setup-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup-business">> = Specific
  const handler = {} as typeof import("../../../app/setup-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup-business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup-business">> = Specific
  const handler = {} as typeof import("../../../app/signup-business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sitemap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sitemap">> = Specific
  const handler = {} as typeof import("../../../app/sitemap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/[staffCode]/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/[staffCode]/book">> = Specific
  const handler = {} as typeof import("../../../app/staff/[staffCode]/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/[staffCode]/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/[staffCode]/bookings">> = Specific
  const handler = {} as typeof import("../../../app/staff/[staffCode]/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/staff/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/login">> = Specific
  const handler = {} as typeof import("../../../app/staff/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/request-reset/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/request-reset">> = Specific
  const handler = {} as typeof import("../../../app/staff/request-reset/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/set-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/set-password">> = Specific
  const handler = {} as typeof import("../../../app/staff/set-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/staff/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/verify-email">> = Specific
  const handler = {} as typeof import("../../../app/staff/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/subscription/expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription/expired">> = Specific
  const handler = {} as typeof import("../../../app/subscription/expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../../app/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../../app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
