var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/verify-email/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1f8e84e6._.js")
R.c("server/chunks/ssr/_d25179f9._.js")
R.c("server/chunks/ssr/_5d93726b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a7e6c3bd._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d8001078._.js")
R.c("server/chunks/ssr/node_modules_0ecec565._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__8be095de._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_verify-email_page_actions_d80a52a5.js")
R.m(63905)
module.exports=R.m(63905).exports
